### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by uppercasem** [tnehil/marthaandtom#4]
Move no comments to bottom of posts, including first page.

**Comment by tnehil** [comment]
Resolved this with 74b7103fac96aa69e02c11096e4f2c0eefd5a403

But now I'm wondering if we should make the date in the meta info right below the headline orange just to have some more visual contrast up there.

**Comment by tnehil** [comment]
I kinda like it orange 082d4cebe2c60d0eeff2ae64a5cfb038b6f70c74
